### ISSUE TITLE
child.stdout not emitting `end` or `close`

### ISSUE THREAD

**Issue by ryanbmilbourne** [Gottox/child_pty#11]
`end` and `close` event listeners for `child.stdout` are not being fired when the streams are closed.  Sample code that produces the issue:

```js
var child = pty.spawn('echo', ['hello'])
child.stdout.on('end', function(){
    console.log('child stdout end')
})
child.stdout.on('close', function(){
    console.log('child stdout close')
})
```

I can produce the issue on my Mac (10.10.5), my TravisCI builds fail (Ubuntu 12.04.5 LTS) and I can replicate the issue with my CentOS 7.1 dev box.

**Comment by Gottox** [comment]
This is expected behaviour on PTYs. Nevertheless, it's not clearly documented.

In contrast to simple pipes, PTYs have no tight coupling between master fd (that's what you see as at stdout) an slave fd (that's what the child process sees as stdout). Both file descriptors can be closed independently.

I'll keep the issue open until I fix the documentation.

**Comment by ryanbmilbourne** [comment]
Okay, thank you for the clarification.  I have an idea of what I can do in leu of these two events.

**Comment by Gottox** [comment]
An easy workaround is to close stdout on the process exit event

**Comment by Gottox** [comment]
The behavior in the upcoming child_pty-3.0.0 has changed. When the child exits, the 'end' event is emitted on the pty.

**Comment by Gottox** [comment]
It would be nice if you could test child_pty master for your use case and give feedback to the changes. :)

**Comment by ryanbmilbourne** [comment]
Thanks for the heads-up. I'll give it a try with the new version and get back to you.
